version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: eye-rest-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - eye-rest-network

  mongo-express:
    image: mongo-express:latest
    container_name: eye-rest-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      TZ: Asia/Bangkok
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo
    networks:
      - eye-rest-network

networks:
  eye-rest-network:
    driver: bridge

volumes:
  mongo-data:
